version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "build"
      - "semver:patch"
    groups:
      charmbracelet:
        patterns:
          - "github.com/charmbracelet/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "build"
      - "semver:patch"
